### ISSUE TITLE
Method not found: 'Void ServiceStack.HostConfig.set_UseSameSiteCookies(Boolean)'

### ISSUE THREAD

**Issue by Beej126** [ServiceStack/Studio#1]
```
> app open studio

Application startup exception: System.MissingMethodException: Method not found: 'Void ServiceStack.HostConfig.set_UseSameSiteCookies(Boolean)'.
   at Studio.AppHost.Configure(Container container)
   at ServiceStack.ServiceStackHost.Init() in C:\Source\Servicestack\src\ServiceStack\ServiceStackHost.cs:line 288
   at ServiceStack.NetCoreAppHostExtensions.UseServiceStack(IApplicationBuilder app, AppHostBase appHost) in C:\Source\Servicestack\src\ServiceStack\AppHostBase.NetCore.cs:line 334
   at Web.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\src\dotnet-app\src\Web\Startup.cs:line 2487
```

opens new app window to a completely blank page
any help?

**Comment by mythz** [comment]
The studio app's binary dependency just needed to rebuilt, you'll now be able to launch it using the latest `app` tool, e.g:

    $ dotnet tool update -g app
    $ app open studio
